In [1]:
import numpy as np

In [20]:
beta = 10.

In [21]:
manifold = np.random.rand(3, 6)

manifold

array([[0.75436819, 0.69166737, 0.85677186, 0.38661258, 0.50022318,
        0.40297796],
       [0.1278122 , 0.60793439, 0.63034984, 0.48914067, 0.72439819,
        0.31402224],
       [0.6770085 , 0.46379861, 0.14284316, 0.56535942, 0.63693174,
        0.76988556]])

In [22]:
def dx_manifold(manifold, idx):
    return(manifold[0, idx])

def dy_manifold(manifold, idx):
    return(manifold[1, idx])

def dz_manifold(manifold, idx):
    return(manifold[2, idx])

In [23]:
X4x = dx_manifold(manifold, 0)
X4y = dy_manifold(manifold, 0)
X4z = dz_manifold(manifold, 0)

#print_trace(X4x, "X4x")

X5x = dx_manifold(manifold, 1)
X5y = dy_manifold(manifold, 1)
X5z = dz_manifold(manifold, 1)

X6x = dx_manifold(manifold, 2)
X6y = dy_manifold(manifold, 2)
X6z = dz_manifold(manifold, 2)

X7x = dx_manifold(manifold, 3)
X7y = dy_manifold(manifold, 3)
X7z = dz_manifold(manifold, 3)

X8x = dx_manifold(manifold, 4)
X8y = dy_manifold(manifold, 4)
X8z = dz_manifold(manifold, 4)

X9x = dx_manifold(manifold, 5)
X9y = dy_manifold(manifold, 5)
X9z = dz_manifold(manifold, 5)

In [24]:
g11 = np.ones(X4x.shape) + beta * (X4x*X4x + X5x*X5x + X6x*X6x + X7x*X7x + 
                                   X8x*X8x + X9x*X9x)
g22 = np.ones(X4y.shape) + beta * (X4y*X4y + X5y*X5y + X6y*X6y + X7y*X7y + 
                                   X8y*X8y + X9y*X9y)
g33 = np.ones(X4z.shape) + beta * (X4z*X4z + X5z*X5z + X6z*X6z + X7z*X7z + 
                                   X8z*X8z + X9z*X9z)
g12 = beta * (X4x*X4y + X5x*X5y + X6x*X6y + X7x*X7y + X8x*X8y + X9x*X9y)
g23 = beta * (X4y*X4z + X5y*X5z + X6y*X6z + X7y*X7z + X8y*X8z + X9y*X9z)
g13 = beta * (X4x*X4z + X5x*X5z + X6x*X6z + X7x*X7z + X8x*X8z + X9x*X9z)

In [35]:
G = np.array([[g11, g12, g13], [g12, g22, g23], [g13, g23, g33]])
print(G)
print(np.linalg.det(G))

[[24.43616894 17.34984589 18.01322031]
 [17.34984589 17.458824   14.38223903]
 [18.01322031 14.38223903 21.11890908]]
922.8391397057328


In [41]:
np.linalg.eig(G)

(array([54.54055555,  3.22219658,  5.2511499 ]),
 array([[-0.63889345, -0.678542  , -0.36248574],
        [-0.51912434,  0.7280064 , -0.4477908 ],
        [-0.56773681,  0.09791544,  0.81736619]]))

In [25]:
#print_trace(g11, "g11")
C11 = g22*g33 - g23*g23
C22 = g11*g33 - g13*g13
C33 = g11*g22 - g12*g12
C12 = -g12*g33 + g13*g23
C23 = -g11*g23 + g13*g12
C13 = g12*g23 - g13*g22

In [26]:
#print_trace(C11, "C11")
detg = g11*C11 + g12*C12 + g13*C13
#print_trace(detg, "detg")

gm05 = 1. / np.sqrt(detg)
#print_trace(gm05, "gm05")

In [27]:
detg

922.8391397057337

In [29]:
gm05

0.032918269554232986

In [44]:
print(np.linalg.inv(G))
np.array([[C11, C12, C13], [C12, C22, C23], [C13, C23, C33]]) / detg


[[ 0.17539624 -0.11631429 -0.07039148]
 [-0.11631429  0.20760836 -0.04217444]
 [-0.07039148 -0.04217444  0.13611215]]


array([[ 0.17539624, -0.11631429, -0.07039148],
       [-0.11631429,  0.20760836, -0.04217444],
       [-0.07039148, -0.04217444,  0.13611215]])

In [36]:
if 0:
    #del g11, g22, g33, g12, g23, g13

    p4 = C11*X4x + C12*X4y + C13*X4z
    p5 = C11*X5x + C12*X5y + C13*X5z
    p6 = C11*X6x + C12*X6y + C13*X6z
    p7 = C11*X7x + C12*X7y + C13*X7z
    p8 = C11*X8x + C12*X8y + C13*X8z
    p9 = C11*X9x + C12*X9y + C13*X9z

    q4 = C12*X4x + C22*X4y + C23*X4z
    q5 = C12*X5x + C22*X5y + C23*X5z
    q6 = C12*X6x + C22*X6y + C23*X6z
    q7 = C12*X7x + C22*X7y + C23*X7z
    q8 = C12*X8x + C22*X8y + C23*X8z
    q9 = C12*X9x + C22*X9y + C23*X9z

    r4 = C13*X4x + C23*X4y + C33*X4z
    r5 = C13*X5x + C23*X5y + C33*X5z
    r6 = C13*X6x + C23*X6y + C33*X6z
    r7 = C13*X7x + C23*X7y + C33*X7z
    r8 = C13*X8x + C23*X8y + C33*X8z
    r9 = C13*X9x + C23*X9y + C33*X9z

    #print_trace(p4, "p4")
 
    #del C11, C22, C33, C12, C23, C13

    # Beltrami operator incrementals
    b4inc = (dpx(p4 * gm05) + dpy(q4 * gm05) + dpz(r4 * gm05)) * np.squeeze(gm05)
    b5inc = (dpx(p5 * gm05) + dpy(q5 * gm05) + dpz(r5 * gm05)) * np.squeeze(gm05)
    b6inc = (dpx(p6 * gm05) + dpy(q6 * gm05) + dpz(r6 * gm05)) * np.squeeze(gm05)
    b7inc = (dpx(p7 * gm05) + dpy(q7 * gm05) + dpz(r7 * gm05)) * np.squeeze(gm05)
    b8inc = (dpx(p8 * gm05) + dpy(q8 * gm05) + dpz(r8 * gm05)) * np.squeeze(gm05)
    b9inc = (dpx(p9 * gm05) + dpy(q9 * gm05) + dpz(r9 * gm05)) * np.squeeze(gm05)